services:
  postgresql-order:
    image: postgres:17.0
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2123
      POSTGRES_DB: product-service
    volumes:
      - ./data:/db/data